framework:
  notifier:
    chatter_transports:
    texter_transports:
    channel_policy:
      # Utilise uniquement le canal "browser" par défaut
      urgent: ["browser"]
      high: ["browser"]
      medium: ["browser"]
      low: ["browser"]
    admin_recipients:
      - { email: admin@example.com }
